<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(NetMinimum);$(NetCurrent)</TargetFrameworks>
    <DebugType>portable</DebugType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);S2223</NoWarn>

  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Issue1417.Tests" />
  </ItemGroup>
  
</Project>
