<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(NetMinimum);$(NetCurrent)</TargetFrameworks>
    <DebugType>portable</DebugType>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <TestingPlatformShowTestsFailure>true</TestingPlatformShowTestsFailure>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TestingPlatformCommandLineArguments)' == ''">
    <!-- Do not activate it for CLI option integration tests, because it will falsify tests -->
    <TestingPlatformCommandLineArguments>$(TestingPlatformCommandLineArguments) --config-file $(RepoRoot)/test/testconfig.json</TestingPlatformCommandLineArguments>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.MTP" />
    <PackageReference Include="xunit.v3.mtp-v2" />
    <PackageReference Include="Microsoft.Testing.Extensions.GitHubActionsReport" />
   </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ClassLibrary1\ClassLibrary1.csproj" />
  </ItemGroup>

</Project>
