<?xml version="1.0" encoding="utf-8"?>
<Project  xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
  <PropertyGroup>
    <TestingPlatformCommandLineArguments Condition=" '$(OS)' == 'Windows_NT'" >$(TestingPlatformCommandLineArguments) --config-file $(RepoRoot)test\testconfig.json</TestingPlatformCommandLineArguments>
    <TestingPlatformCommandLineArguments Condition=" '$(OS)' != 'Windows_NT'" >$(TestingPlatformCommandLineArguments) --config-file $(RepoRoot)test/testconfig.json</TestingPlatformCommandLineArguments>
  </PropertyGroup>
  
</Project>