<Project>
  <PropertyGroup>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <XunitV3Version>3.2.2</XunitV3Version>
    <XunitRunnerVisualstudioVersion>3.1.5</XunitRunnerVisualstudioVersion>
    <CoverletVersion>10.0.1-preview.1.gf54f2f5d4d</CoverletVersion>
  </PropertyGroup>
  <ItemGroup>
    <GlobalPackageReference Include="SonarAnalyzer.CSharp" Version="10.25.0.139117" />
    <GlobalPackageReference Include="Nerdbank.GitVersioning" Version="3.9.50" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="coverlet.MTP" Version="$(CoverletVersion)" />
    <PackageVersion Include="coverlet.msbuild" Version="$(CoverletVersion)" />
    <PackageVersion Include="coverlet.collector" Version="$(CoverletVersion)" />
    <PackageVersion Include="Google.Protobuf" Version="3.34.1" />
    <PackageVersion Include="Grpc.AspNetCore" Version="2.76.0" />
    <PackageVersion Include="Grpc.Net.Client" Version="2.76.0" />
    <PackageVersion Include="Grpc.Tools" Version="2.80.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
    <PackageVersion Include="Microsoft.AspNetCore.TestHost" Version="10.0.7" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.7" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="MSTest" Version="4.2.2" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="NUnit" Version="4.5.1" />
    <PackageVersion Include="NUnit.Analyzers" Version="4.13.0" />
    <PackageVersion Include="NUnit3TestAdapter" Version="6.2.0" />
    <PackageVersion Include="Microsoft.Testing.Extensions.TrxReport" Version="2.2.2" />
    <PackageVersion Include="xunit.v3.mtp-v2" Version="$(XunitV3Version)" />
    <PackageVersion Include="xunit.v3.runner.msbuild" Version="$(XunitV3Version)" />
    <PackageVersion Include="System.CommandLine" Version="2.0.7" />
  </ItemGroup>
</Project>
