<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(NetMinimum);$(NetCurrent)</TargetFrameworks>
    <DebugType>portable</DebugType>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <TestingPlatformShowTestsFailure>true</TestingPlatformShowTestsFailure>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <NoWarn>$(NoWarn);S125;S2699;S4144;S1118;CA1822;CA1852</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Issue1334.Tests\CoverletReproTest.cs" Link="CoverletReproTest.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <!--<PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />-->
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ClassIssue1334\ClassIssue1334.csproj" />
  </ItemGroup>

</Project>
