<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DebugType>portable</DebugType>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <DisableTestingPlatformServerCapability>true</DisableTestingPlatformServerCapability>
    <TestingPlatformDotnetTestSupport>false</TestingPlatformDotnetTestSupport>
    <TestingPlatformShowTestsFailure>false</TestingPlatformShowTestsFailure>
    <UseMicrosoftTestingPlatformRunner>false</UseMicrosoftTestingPlatformRunner>
    <NoWarn>$(NoWarn);S2094,S2326,S1144,S2360,S2094</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="xunit.v3" VersionOverride="3.2.2" />
    <PackageReference Include="Microsoft.Testing.Platform.MSBuild" VersionOverride="1.9.1" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" VersionOverride="1.9.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ClassIssue2036\ClassIssue2036.csproj" />
  </ItemGroup>

</Project>