<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(NetMinimum);$(NetCurrent)</TargetFrameworks>
    <DebugType>portable</DebugType>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <EnableNUnitRunner>true</EnableNUnitRunner>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <TestingPlatformShowTestsFailure>true</TestingPlatformShowTestsFailure>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="NUnit3TestAdapter" />
    <!-- MTP result reporters -->
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
    <PackageReference Include="coverlet.MTP" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ClassLibrary1\ClassLibrary1.csproj" />
  </ItemGroup>

  <Target Name="ShowEnableNUnitRunner" BeforeTargets="Build" Condition="'$(VerboseBuild)' == 'true'">
    <Message Text="EnableNUnitRunner is set to: $(EnableNUnitRunner)" Importance="High" />
  </Target>

</Project>
